VCST-1938: extra search notification activity feed criterias
VirtoCommerce/vc-module-notification pull request #163
Opened 2024-10-04 15:49 UTC by mihey8800

feat: added new fields and unit tests

## Description

## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/VCST-1938
### Artifact URL:

2024-10-07 10:14 UTC, OlegoO approved these changes

2024-10-07 10:24 UTC, artem-dudarev requested changes
Need to fix tests

2024-10-07 11:38 UTC, artem-dudarev requested changes

2024-10-07 11:38 UTC, artem-dudarev commented on tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationMessageSearchServiceUnitTests.cs
> +        };
Need to add more entities to each filtering test to make sure the filtering actually works.
Now we have one input entity and one ouput entity - this doesn't show any filtering.

2024-10-07 11:38 UTC, artem-dudarev commented on tests/VirtoCommerce.NotificationsModule.Tests/UnitTests/NotificationMessageSearchServiceUnitTests.cs
> +        Assert.Contains(keyword, firstResult.LastSendError);
This looks like all fields must contain the keyword, but it can only be in one of them.

2024-10-08 09:57 UTC, artem-dudarev approved these changes

2024-10-10 07:40 UTC, merged