VP-0: Refactor migrations to simplify queries
VirtoCommerce/vc-module-notification pull request #56
Opened 2020-09-15 11:38 UTC by akak1977

2020-10-13 13:55 UTC, kostyrin requested changes

2020-10-13 13:55 UTC, kostyrin commented on src/VirtoCommerce.NotificationsModule.Data/Migrations/20190528144557_InitialNotifications.cs
> +                            WHERE Language='en-US'
remove

2020-10-13 13:55 UTC, kostyrin commented on src/VirtoCommerce.NotificationsModule.Data/Migrations/20190528144557_InitialNotifications.cs
> +							  left outer join [Notification] n
all command chars need to be Upper case or use CAPS LOCK

2020-10-13 13:55 UTC, kostyrin commented on src/VirtoCommerce.NotificationsModule.Data/Migrations/20190528144557_InitialNotifications.cs
> -                                  , (SELECT TOP 1 n.Id FROM [Notification] n WHERE n.[Type] = pn.[Type])
also remove 'SELECT TOP 1..' on line 293

2020-10-13 13:55 UTC, kostyrin commented on src/VirtoCommerce.NotificationsModule.Data/Migrations/20190528144557_InitialNotifications.cs
> +								  left outer join [Notification] n
UPPER CASE

2020-10-14 09:42 UTC, yecli commented on src/VirtoCommerce.NotificationsModule.Data/Migrations/20190528144557_InitialNotifications.cs
> +	                            SELECT [NotificationTypeId], MAX([Id]) [Id] FROM [PlatformNotificationTemplate]
Why are you using MAX, as it was TOP 1 before? Seems MIN is more suitable

2020-10-14 10:00 UTC, merged